Twitter_V1/Controllers/HomePageController.cs
using Microsoft.AspNetCore.Mvc;
using Twitter_V1.Models;

namespace Twitter_V1.Controllers
{
    public class HomePageController : Controller
    {

        // Repository class where all tweet related operations are performed
        TweetRepository TRep = new TweetRepository();



        public ActionResult Feed() {
            if (HttpContext.Request.Cookies.ContainsKey("UserEmail"))
            {
                return View("Feed");
            } 
            else
            {
                // Storing error message in the viewbag        
                ViewBag.Message = "Login or Signup to Access the Page";
                return RedirectToAction("index", "LoginSignup");
            }
            
        }


        // This function is called when user tweets something
        [HttpPost]
        public async Task<ViewResult> TweetForm(string Text)
        {
            Tweet t = new Tweet
            {
                Name = Request.Cookies["UserName"],
                Email = Request.Cookies["UserEmail"],
                Text = Text
            };

            ViewBag.Message = await TRep.AddTweetAsync(t);

            return View("Feed");
        }
    }
}

Twitter_V1/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using Twitter_V1.Models;
using System.IO;
using Microsoft.AspNetCore.Http;


namespace Twitter_V1.Controllers
{
    public class ProfileController : Controller
    {
        TweetRepository TRep = new TweetRepository();
        UserRepository URep = new UserRepository();


        public ActionResult UserProfile() {
            if (HttpContext.Request.Cookies.ContainsKey("UserEmail"))
            {
                return View("UserProfile");
            } else
            {
                // Storing error message in the viewbag        
                ViewBag.Message = "Login or Signup to Access the Page";
                return RedirectToAction("index", "LoginSignup");
            }
        }

        // This function is called when user deletes tweets 
        [HttpPost]
        public async Task<ViewResult> DeleteTweet(int TweetId)
        {
            await TRep.DeleteTweetAsync(TweetId);

            return View("UserProfile");
        }





    }
}

Twitter_V1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EAD Twitter Clone</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.rtl.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.rtl.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet" />

	<link href="~/lib/bootstrap/dist/css/bootstrap-reboot.min.css" rel="stylesheet" />
	<link href="~/lib/bootstrap/dist/css/bootstrap-reboot.rtl.min.css" rel="stylesheet" />
	<link href="~/lib/bootstrap/dist/css/bootstrap-reboot.rtl.css" rel="stylesheet" />
	<link href="~/lib/bootstrap/dist/css/bootstrap-reboot.css" rel="stylesheet" />

	<link href="~/lib/bootstrap/dist/css/bootstrap-utilities.min.css" rel="stylesheet" />
	<link href="~/lib/bootstrap/dist/css/bootstrap-utilities.rtl.min.css" rel="stylesheet" />
	<link href="~/lib/bootstrap/dist/css/bootstrap-utilities.rtl.css" rel="stylesheet" />
	<link href="~/lib/bootstrap/dist/css/bootstrap-utilities.css" rel="stylesheet" />
</head>
<body>
    @{
        Context.Request.Cookies.TryGetValue("UserId", out string UserId);
    }

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="LoginSignup" asp-action="Index">Twitter Clone EAD</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-controller="LoginSignup" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-controller="HomePage" asp-action="Feed">Feed</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-controller="Profile" asp-action="UserProfile" asp-route-id="@UserId">Profile</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    

    <div>
        @RenderBody()
    </div>
    <div>
        <!-- Rendering the Footer Section which we have defined in Profile and Feed Pages-->
        @RenderSection("Footer",false) 
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

Twitter_V1/Views/Shared/_TweetFormView.cshtml
<section style="background-color: #eee;">
  <div class="container my-5 py-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 col-lg-10 col-xl-8">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-start align-items-center">
              <img class="rounded-circle shadow-1-strong me-3"
                src="https://www.seekpng.com/png/detail/41-410093_circled-user-icon-user-profile-icon-png.png" alt="avatar" width="60"
                height="60" />
              <div>
                <h6 class="fw-bold text-primary mb-1">
                                    @{
                                        Context.Request.Cookies.TryGetValue("UserName", out string value);
                                    }
                                    @value
                </h6>
                <p class="text-muted small mb-0">
                  What's on your mind?
                </p>
              </div>
            </div>

          </div>
          <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
            <div class="d-flex flex-start w-100">
              <div class="form-outline w-100">
                <textarea class="form-control" id="textAreaExample" rows="4"
                  style="background: #fff;"></textarea>
                <label class="form-label" for="textAreaExample">Tweet</label>
              </div>
            </div>
            <div class="float-end mt-2 pt-1">
              <button type="button" class="btn btn-primary btn-sm">
                Post Tweet
              </button>
              <button type="button" class="btn btn-outline-primary btn-sm">
                Cancel
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>